### ISSUE TITLE
Create an interface for the consul client class.

### ISSUE THREAD

**Issue by SeanFarrow** [PlayFab/consuldotnet#16]
Hi,

It would be nice to have an interface for the consul client class so that dependency injection/unit testing with mocks could be done properly.
I'm happy to do this and submit a pull request.

**Comment by highlyunavailable** [comment]
I think I know what you're looking for, and that's actually something I was already writing due to our own testing needs at PlayFab. I'm working on a fairly major rewrite of a few core portions of the client class code to clean up a bunch of cruft.

Can you give me a couple of examples of what you'd like to see as an interface (or interfaces)? I think I've got mostly what you want in my own repo but I'd like to make sure it would suit your needs as well.

**Comment by SeanFarrow** [comment]
Hi,

Essentially, I need an interface to the client, such that I can mock this out in tests.
Where are you guys based at PlayFab?
Cheers
Sean.

**Comment by highlyunavailable** [comment]
Yeah, I know what you mean for testing. This is already halfway done on my side, so I'd just say the best option is to wait for a new version.

**Comment by SeanFarrow** [comment]
Cool, any time frame as yet?
Cheers
Sean.

**Comment by highlyunavailable** [comment]
Probably a few days.

**Comment by highlyunavailable** [comment]
This request is completed as of 94add6b3 (release 0.5.2.61 on nuget).

Please note there is a breaking change in this version - the `Client` class is now `ConsulClient` and I've had to change the return types of all of the Lock classes and the endpoints to be interfaces. If you use `var` to declare your variables it should be of minimal impact.

**Comment by gdavison** [comment]
IConsulClient isn't public, though all the others are.

**Comment by highlyunavailable** [comment]
Uh oh, sorry about that.

**Comment by highlyunavailable** [comment]
This should be resolved as soon as tag 0.5.2.62 builds.

https://ci.appveyor.com/project/highlyunavailable/consuldotnet/build/0.5.2.74-0.5.2.62
