### ISSUE TITLE
Serialization/Dependency Questions

### ISSUE THREAD

**Issue by kharabasz** [PlayFab/consuldotnet#22]
Hello - would you entertain accepting a pull request that would break the dependency of your project on Json.Net? This could be achieved by exposing a serialization interface and moving the Json.net specific code into a separate nuget package as an adapter.

**Comment by highlyunavailable** [comment]
Tell me more! The reason I'm using json.net in package is I needed easy json serialization when I wrote it. If another method can also handle empty fields and custom type serialization and deserialization (e.g. golang durations) as well then it should be ok. It sounds like the PR would need to recreate some of that functionality since many of the Consul structs have a bunch of fields and behave slightly differently depending on which fields are there, e.g ttl vs script health checks.

**Comment by highlyunavailable** [comment]
Good example: https://github.com/PlayFab/consuldotnet/blob/master/Consul/Agent.cs

All the ShouldSerialize* methods and the attributes control Json.net.

But yes, I would be open to a PR for this.

**Comment by highlyunavailable** [comment]
@kharabasz I'm going to close this issue since your question has been answered - I look forward to your PR if you're still looking working on this, though. If you need any additional assistance around this, feel free to open another issue or email me at the email in my github profile.

**Comment by kharabasz** [comment]
@highlyunavailable No problem, I haven't had time to work on this yet, but will try to get a pull request together soon. Thanks!
