### ISSUE TITLE
The type or namespace name 'PushStreamContent' could not be found

### ISSUE THREAD

**Issue by crazybird** [PlayFab/consuldotnet#41]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'PushStreamContent' could not be found (are you missing a using directive or an assembly reference?)	Consul	C:\Users\xxx\Desktop\consuldotnet-master\consuldotnet-master\Consul\Client.cs	949	Active

**Comment by highlyunavailable** [comment]
Thanks for submitting this issue. I'm going to need more information though, since I'm not able to reproduce this error on either my local computer or the AppVeyor build server, both of which are running Visual Studio 2015.

The `PushStreamContent` class is provided by Microsoft in the `System.Net.Http` library via the ASP.NET Web API 2: https://msdn.microsoft.com/en-us/library/system.net.http.pushstreamcontent.pushstreamcontent%28v=vs.118%29.aspx

These should be included with ASP.NET 4.5 as far as I can tell, my reference path is `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Net.Http.dll`

What version of Visual Studio are you running, and do you have the `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5` path or are these somewhere else on disk? You may want to try deleting and re-adding the references as well and see if your DLLs are located somewhere else.

**Comment by egarson** [comment]
I got the same issue trying to compile 0.6.1.4 using xbuild 12.0 (mono 4.2.2.0). I look forward to the PR as well :)
Thank you for consuldotnet, it's been a great pleasure to use.

**Comment by highlyunavailable** [comment]
@egarson that helps a lot - I've actually been trying to figure out how people are getting this error.

Can you please try [0.6.3.2](https://github.com/PlayFab/consuldotnet/releases/tag/0.6.3.2) and see if it fixes the issue? Feel free to open a new issue or re-open this if you're getting more errors. I haven't tested it on non-Windows/non-Visual Studio though I would be extremely interested in someone helping with that.

**Comment by egarson** [comment]
My pleasure @highlyunavailable, I am happy to help.
The [0.6.3.2](https://github.com/PlayFab/consuldotnet/releases/tag/0.6.3.2) resolves the issue: well done, and thank you for a very fast turnaround!
Note: xbuild on the command line yielded a plethora of issues relating to Newtonsoft.Json which I resolved by loading the project up in MonoDevelop, right-clicking that assembly in "Packages" and selecting, "Update". Building within MonoDevelop then succeeds, but yields two minor warnings, fwiw:
```
Lock.cs(156,22): warning CS0414: The private field `Consul.Lock._monitorTask' is assigned but its value is never used
Semaphore.cs(249,22): warning CS0414: The private field `Consul.Semaphore._monitorTask' is assigned but its value is never used`
```
When loading the solution in MonoDevelop 5.10, Consul.Test displays a warning, "This project type is not supported by MonoDevelop". I've seen this before when the ToolsVersion=4.0 in the associated.csproj, but it is "correct" at version 12.0. I tried a couple of things to resolve this small issue but was unable to. 
Kind regards

**Comment by crazybird** [comment]
@highlyunavailable 
My development environment is VS2015 Updata1.
I found  the PushStreamContent class is provided by System.Net.Http.Formatting.dll.
I download this dll from Nuget ,  and  add  reference.

Now I can complete the function based on Consul in Window or Linux.
I completed the mono program since the discovery of Docker image based on consuldotnet.

Thanks consuldotnet.Thank you for consuldotnet.

**Comment by egarson** [comment]
I forgot to mention: the good mono folks have an implementation of [PushStreamContent](https://github.com/mono/aspnetwebstack/blob/6248bfd24c31356e75a31c1b1030d4d96f669a6a/src/System.Net.Http.Formatting/PushStreamContent.cs) in their [aspnetwebstack](https://github.com/mono/aspnetwebstack) sub-project, so further work-arounds "shouldn't" *have been* strictly necessary. I had trouble compiling it, but I didn't try all that hard, to be honest.

**Comment by highlyunavailable** [comment]
Glad you both find this library useful! I set up a copy of MonoDevelop on my Linux box to try this out but I need to figure out the CI story to make sure there are Linux builds on checkin.

@crazybird you shouldn't need to add any additional references now because of the removal of `PushStreamContent`. I was able to compile the library with no edits using XBuild on Linux.

@egarson:
* I think those two warnings are legitimate, I did some refactoring around the monitoring of locks that probably removed the references to the monitoring tasks. For some reason VS2015 doesn't yell about them. I'll clean it up.
* Consul.Test probably doesn't work because it started life as a MSTest Unit Test Project and I hand-converted it to XUnit. Since there is no MSTest in MonoDevelop, that's probably why it doesn't work. I think I just need to recreate the test project as an XUnit project and copy all the test files over.
* I didn't get any warnings at all about Newtonsoft.Json when I built just now on Linux, but if you're compiling the project yourself, updating is absolutely the right course of action. JSON encoding has been a problem for this whole project - either people have an old version of Json.NET, which my reference conflicts with, or have a newer version, which my code doesn't want to load because it's newer than what's referenced. In reality I use the simplest possible JSON stuff - serialize, deserialize from/into classes, that's it.

Thanks for the feedback, though - it really helps.
