### ISSUE TITLE
Consul.Test doesn't like Mono

### ISSUE THREAD

**Issue by egarson** [PlayFab/consuldotnet#46]
"Core" Consul version 0.6.3.3 (bleeding edge as I write this) loads into MonoDevelop ok (which is just a heuristic for getting along with Mono on my Xubuntu / mono 4.2.2 machine). However, Consul.Test is unhappy with more than just the xunit.runner.visualstudio.2.1.0 Import element declarations in Consul.Test.csproj.
I'd like to potentially contribute to this project, but I'm not able to resolve the above "safely" for users on Windows. If this were resolvable, I'd be in a position to run the tests....
Kind regards

**Comment by highlyunavailable** [comment]
As I said in https://github.com/PlayFab/consuldotnet/issues/41#issuecomment-188852361:
> Consul.Test probably doesn't work because it started life as a MSTest Unit Test Project and I hand-converted it to XUnit. Since there is no MSTest in MonoDevelop, that's probably why it doesn't work. I think I just need to recreate the test project as an XUnit project and copy all the test files over.

Ideally this whole project gets converted to the new ASP.NET version (with the project.json etc) but that's a ton of work because a lot of namespaces changed for dnx50.

I'll try to just move this to an xunit test project in VS and see what happens.

**Comment by highlyunavailable** [comment]
Okay, so the `develop` branch now actually loads in monodevelop but I really don't know how to get it to actually show the unit tests in monodevelop. I got a super hacky method involving the xunit console runner to actually run the tests (which fails some of them in spectacular ways!) but it still doesn't show the actual monodevelop tests window. Any thoughts on how to get this working in monodevelop? If it was DNX I could just use `dnx test` for all this.

**Comment by highlyunavailable** [comment]
I'm working on a dnxcore branch as well - https://github.com/PlayFab/consuldotnet/tree/dnxcore50 but it doesn't seem to pass tests/actually work with the Core CLR - a lot of the tests fail with
       Consul.KeyNotFoundException : Failed to read prefix
      ---- Newtonsoft.Json.JsonReaderException : JSON integer 16210313421097356768 is too large or small for an Int64. Path '[0].Flags', line 1, position 112.

Due to this line:
https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/JsonTextReader.cs#L1977

May be worth a try with monodevelop to see if it can read the project.jsons better.

**Comment by egarson** [comment]
What about just using NUnit? ASP.NET seems like a large dependency to meet this requirement. We use NUnit for cross-platform development and it works great.

**Comment by egarson** [comment]
I did note what you said in issue #41, I just thought a new, separate issue for Mono/monodevelop compatibility would be easier to manage, particularly for new folks.

**Comment by highlyunavailable** [comment]
NUnit is fine, I just don't want to convert all the tests a third time - I already went from MSTest to XUnit to support DNXCore in the first place. And agreed on your last comment. I was just reiterating it.

**Comment by highlyunavailable** [comment]
At this point, the XUnit tests are externally runnable via the XUnit console runner and I don't have plans to convert them to NUnit. I'm able to open the Consul.Test project and edit files in MonoDevelop now though, so it might be possible to set up some sort of custom action as a "debug action" or something on the test project that starts the console runner and connects the MonoDevelop debugger to it.
