### ISSUE TITLE
Make Consul.Net more unit-test friendly

### ISSUE THREAD

**Issue by jhickson** [PlayFab/consuldotnet#48]
Hi,

I'm not able to create unit tests that handle the response from `ICatalogEndpoint.Service` (and similar calls) because `QueryResult<>.Response` has an internal setter.  Could the setter be made public, please?  I'm guessing that's the least disruptive means of solving this problem.

Thanks.

**Comment by highlyunavailable** [comment]
After looking through the code I'm not entirely sure why I made the setter internal in the first place, to be quite honest.

There's a couple other places you might run into problems since the CreateIndex/ModifyIndex is usually a private setter. Do you need private setters to be public setters as well (e.g. Consul.KVPair.ModifyIndex)? I made those private because they technically should only be set by Consul responses but I guess if the developer is assigning to ModifyIndex they've presumably got a good reason so it really doesn't matter if they're public setters.

**Comment by highlyunavailable** [comment]
Alright @jhickson , I've made all the bits that need to be have public setters from what I can tell. AppVeyor keeps failing intermittently but my local builds are working so it may be a bit of time before I produce a package, but this should be fixed next release.

**Comment by highlyunavailable** [comment]
Fixed in 0.6.3.6: https://www.nuget.org/packages/Consul/0.6.3.6

Have fun, and please let me know if you run into any other issues.

**Comment by jhickson** [comment]
Hi @highlyunavailable, thanks for that.  I'll update and see how I go.

Sorry for the radio silence but I headed home from work not long after adding the issue and have just got in this morning.

I'm not sure about the CreateIndex/ModifyIndex setters as I'm not currently using them but I'll update you if I do.

**Comment by highlyunavailable** [comment]
No problem at all. I just made them publicly settable anyway because I figured that someone would need them.
