### ISSUE TITLE
Connect to remote server

### ISSUE THREAD

**Issue by amgadfahmi** [PlayFab/consuldotnet#54]
Sorry about the question but the documentation doesn't not having enough info. 
Can this library connect to remote Consul server (not localhost and default port) to register itself as a service for specific data center !

**Comment by highlyunavailable** [comment]
It can. Generally you don't want to because that's now how Consul is designed to be used (each machine should have an agent that talks to a local server cluster, see the [architecture](https://www.consul.io/docs/internals/architecture.html) docs) and it's generally much more efficient to run an agent locally and talk to it since it has a variety of tricks it uses to make API calls faster (e.g. pipelining). However, if you really need to connect to a remote consul server with this, you'd create a new `ConsulClientConfiguration` object with custom Address URI and use it in the Client's constructor like so:

```c#
var remoteConfig = new ConsulClientConfiguration()
{
    Address = new Uri("http://remote.server:5000")
};
using (var client = new ConsulClient(remoteConfig))
{
    // Do a thing
}
```

Let me know if you have any other questions or issues. Thanks!
