### ISSUE TITLE
Is ConsulClient thread safe?

### ISSUE THREAD

**Issue by MichaelLogutov** [PlayFab/consuldotnet#62]
Hello.
I want to use one ConsulClient for application - is it thread safe? Or I should just create it (in using) wherever I need cause the creation has minimal overhead and internal connection pooling is used?

**Comment by highlyunavailable** [comment]
Yes, the `ConsulClient` class is threadsafe and should be shared across all threads in an application. It is more efficient to create one and share it because a single TCP connection can be held open for all requests on that `ConsulClient` - internally it's constructing an `HttpClient` for every `ConsulClient` so setup and teardown costs of that class apply as well.

There would be a data race issue (which is being fixed in 0.7.0 with new semantics around construction of the client) if you modify any properties of the client or its underlying `HttpClient` while using the Client in another thread, but if you do share it across threads and run into any sort of error or race condition due to multithreading other than the previously stated caveat, it is a bug and should be reported. The Lock and Semaphore classes are also threadsafe as you might expect, but the other types (e.g. `KVPair`) that are simply data container classes are not threadsafe.

Please let me know if you have any further questions and I'll be happy to re-open this to address those as well.

**Comment by kpa6uk** [comment]
We faced an issue with k/v monitoring API and one ConsulClient instance for all threads.

Scenario: we have a class thatr provides configuration parameters for application stored in consul k/v. When we create an instance of this class, all values are get from k/v store. After each value fetched, we start its value monitoring by this code:

	var queryOprions = new QueryOptions
	{
		WaitIndex = lastModifyIndex,
		WaitTime = TimeSpan.FromMinutes(10)
	};
	monitoringGet = await consulClient
		.KV
		.Get(valueKeyPath, queryOprions, ct);

So each monitoring call blocks any another calls.
