### ISSUE TITLE
Is consistency modes exposed via Agent?

### ISSUE THREAD

**Issue by Eibwen** [PlayFab/consuldotnet#70]
I see your `client.KV.Get` supports QueryOptions to set consistency modes.  But I'm not seeing any tests or documentation on how to use that on `client.Agent.Services`.  Or did i misread consul docs and that isn't supported on service lookups?

For reference: https://www.consul.io/docs/agent/http.html#consistency-modes

**Comment by highlyunavailable** [comment]
The Agent endpoint is used to interact with the [local agent](https://www.consul.io/docs/agent/http/agent.html), where "local" means "the one that the API is connected to." in this context. This means that a consistency mode would have no effect since you're talking to the context of the exact agent you are currently connected to and asking it for information it can provide in authoritative manner, rather than the cluster as a (optionally) consistent whole. If you want to use consistency modes for service lookups, use the client.[Catalog](https://www.consul.io/docs/agent/http/catalog.html) endpoint if you don't care about health states or the client.[Health](https://www.consul.io/docs/agent/http/health.html) endpoint if you want the catalog filtered by health states.
