### ISSUE TITLE
DNS Lookup Service

### ISSUE THREAD

**Issue by huyjack178** [PlayFab/consuldotnet#73]
Currently, I use Consul for service discovery in ASP.NET Application. But I don't know how to use DNS lookup in Consul Client .NET

**Comment by highlyunavailable** [comment]
DNS lookup is not implemented in Consul.NET because .NET and the operating system provide tools to do that natively. The [System.Net.Dns](https://msdn.microsoft.com/en-us/library/system.net.dns(v=vs.110).aspx) class will help you if Consul is configured to be your operating system's DNS server or (in the case of a linux system) you've got DNSMasq configured to map your custom consul domain to the local agent's port.

If you need to somehow reach out to the agent's DNS server without it being in your OS's DNS settings, then you probably have to use a third party DNS client library such as [ARSoft.Tools.Net](https://www.nuget.org/packages/ARSoft.Tools.Net) - note I've never used this and it's just the result of a search, but it does have a `DNSClient` class that allows specifying of the server IP.

**Comment by MattRyan** [comment]
System.Net.Dns does not appear to support getting SRV records from DNS. Without this functionality port information cannot be retrieved. Do you have a recommended library for supporting this feature? If not would inclusion of such a feature to this library be warranted?

**Comment by highlyunavailable** [comment]
@MattRyan If you're using this library already, I would strongly suggest that you just use the Consul Health endpoint to get the IP addresses/ports since it's somewhat more fully featured in the context of Consul than DNS SRV records. As I said in my comment above, there are libraries that implement this functionality - the most popular by Nuget downloads seems to be https://www.nuget.org/packages/ARSoft.Tools.Net/ . There are others of course, but it is not something that I think needs to be added to this library, since it works at somewhat cross-purposes with the HTTP API to use DNS if HTTP is available.
