### ISSUE TITLE
KV operations in .net core platform are very slow

### ISSUE THREAD

**Issue by vincentshow** [PlayFab/consuldotnet#75]
I added "Consul": "0.7.0.4" to my .net core 1.0 project via nuget in vs2015. The problem was all KV operations on Consul took 5000ms+ while no more than 10ms in .net framework 4.5 platform. Consul version is 0.7.1 in centos7. Here is my test code.

        static async Task TestConsulKV(string flag)
        {
            Stopwatch _watcher = new Stopwatch();
            Stopwatch _subWatcher = new Stopwatch();
            _watcher.Start();
            _subWatcher.Start();
            var _count = 0;
            var _consul = new ConsulClient(config => config.Address = new Uri("http://172.18.70.71:8500"));
            for (; _count < 5; _count++)
            {
                var _key = $"schema/test/{_count}";
                var _existsPair = await _consul.KV.Get(_key);
                if (_existsPair.Response != null)
                {
                    Console.WriteLine(Encoding.UTF8.GetString(_existsPair.Response.Value));
                }
                var _kvPair = new KVPair(_key);
                _kvPair.Value = Encoding.UTF8.GetBytes($"{flag ?? "default"}{_count}");
                _consul.KV.Put(_kvPair).Wait();

                //if (_count % 100 == 0)
                //{
                Console.WriteLine($"finished {_count} in {_subWatcher.ElapsedMilliseconds}ms");
                _subWatcher.Restart();
                //}
            }
            Console.WriteLine($"all finished in {_watcher.ElapsedMilliseconds}ms");
        }

.net core result:
![netcore](https://cloud.githubusercontent.com/assets/6469836/21477832/9fcdb076-cb80-11e6-8d5c-84e8651582c4.png)

netframework4.5 result:
![netframework451](https://cloud.githubusercontent.com/assets/6469836/21477860/dcffbf48-cb80-11e6-8756-a23c0ac3820a.png)

**Comment by highlyunavailable** [comment]
Ensure you are not using a proxy at the system level, since it feels like a
timeout and others have had the same issue with a proxy or VPN as the cause.

**Comment by vincentshow** [comment]
My network setting is controlled at company level. There should not have proxy as I know. Even though there is proxy, why the operations are fast in .net framework 4.5?

**Comment by highlyunavailable** [comment]
I'm going off of a previous issue with this same behavior: https://github.com/PlayFab/consuldotnet/issues/66

As I said in that issue, typical network performance for both .NET and .NET Core is around what you're seeing in the .net 4.5 test there, and all of the operations that this software does during testing all complete in a very short period (usually 1-2ms) as well on both .NET Core and .NET 4.5. Typically network performance issues are caused by things on the developer's machine, since this uses the standard .NET networking APIs.

The reason .NET 4.5 and .NET Core differ I can only guess at, but I will say that there are differences in how they configure system proxies etc. and that probably one is picking up a proxy while the other isn't.

You may want to try to configure your `ConsulClient` like this as a test:
```c#
var _consul = new ConsulClient(
    config => config.Address = new Uri("http://172.18.70.71:8500"),
    null,
    h => { h.UseProxy = false; h.Proxy = null; });
```

I also suggest starting a _local_ Consul server as described in the README and seeing if the performance issues persist when using this API against the server running on localhost.

**Comment by vincentshow** [comment]
You are right. Thanks.
