### ISSUE TITLE
KV Folders

### ISSUE THREAD

**Issue by baldwinjim** [PlayFab/consuldotnet#81]
Is there anyway to just get folders from the KV?  

For example:

environments
 ->test
 ->uat

Basically, is there some way to query environments and get the names of the folders test and uat?

**Comment by highlyunavailable** [comment]
Getting recursive data from the KV store is weird because it has no real concept of paths - a path is just a separated string. In other words, given the keys "a", "a/b" and "a/c", b and c are not children of a - they just look like they are due to what we expect slashes to do.

`Keys("environments/", "/")` or `Keys("environments", "")` would return only the key names - the second argument is a "separator" which means that passing a "/" will only show the first level beneath environments. Empty string or null will make it recursively list all key names.

Behavior of the specific passed strings is detailed in the [HTTP API](https://www.consul.io/docs/agent/http/kv.html) docs for the KV store. Specifically, `Keys(prefix, sep)` is equivalent to calling `/v1/kv/prefix?keys&separator=sep` and `Keys(prefix, "")` is equivalent to calling `/v1/kv/prefix?keys`.
